// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: approved_requests.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApprovedRequest = `-- name: CreateApprovedRequest :exec
INSERT INTO approved_requests (
    stream_id,
    client_id,
    resource,
    cost,
    approved_at,
    remaining
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (stream_id) DO NOTHING
`

type CreateApprovedRequestParams struct {
	StreamID   string             `json:"stream_id"`
	ClientID   string             `json:"client_id"`
	Resource   string             `json:"resource"`
	Cost       int32              `json:"cost"`
	ApprovedAt pgtype.Timestamptz `json:"approved_at"`
	Remaining  int32              `json:"remaining"`
}

func (q *Queries) CreateApprovedRequest(ctx context.Context, arg CreateApprovedRequestParams) error {
	_, err := q.db.Exec(ctx, createApprovedRequest,
		arg.StreamID,
		arg.ClientID,
		arg.Resource,
		arg.Cost,
		arg.ApprovedAt,
		arg.Remaining,
	)
	return err
}
