// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApprovedRequest struct {
	StreamID   string             `json:"stream_id"`
	ClientID   string             `json:"client_id"`
	Resource   string             `json:"resource"`
	Cost       int32              `json:"cost"`
	ApprovedAt pgtype.Timestamptz `json:"approved_at"`
	Remaining  int32              `json:"remaining"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
