port 26379
dir /tmp

sentinel resolve-hostnames yes
sentinel announce-hostnames yes
sentinel monitor rate-limiter-primary redis-primary 6379 2
sentinel down-after-milliseconds rate-limiter-primary 5000
sentinel parallel-syncs rate-limiter-primary 1
sentinel failover-timeout rate-limiter-primary 30000
